SET QUOTED_IDENTIFIER ON;  -- bắt buộc cho filtered index (open-row); sqlcmd mặc định OFF
SET ANSI_NULLS ON;
GO
/*==============================================================================
  SDI MODULE — TABLES (SQL Server)
  HAI CẤP:
    - MASTER (danh mục mẫu/chiến lược): mã `C_MASTER_CODE` (PK T_MASTER_PORTFOLIO).
      Bảng tổng hợp master-level: T_MASTER_PORTFOLIO(_TICKER), T_MASTER_NAV_BALANCE,
      T_MASTER_HOLDING_BALANCE, T_MASTER_INDEX_DAILY, T_MASTER_NAV_CURRENT (key C_MASTER_CODE).
    - SUB-ACCOUNT (tiểu khoản, customer-level): KH đầu tư 1 master → cấp 1 sub-account, mã
      `C_SI_ACCOUNT` (VARCHAR20, = CUST_CODE + đuôi, sinh khi mở). Close + reopen master ⇒ sub-account
      MỚI (mã khác) → 1 KH có NHIỀU sub-account/master theo thời gian (tối đa 1 ACTIVE/lúc).
      ⇒ MỌI bảng customer-level KHÓA theo `C_SI_ACCOUNT` (giữ C_CUST_CODE, C_MASTER_CODE denormalized
      để query + tổng hợp master).
  Naming: T_/C_ UPPERCASE. Khóa surrogate public GUID `PK_<table>` (NEWID, IDOR-safe). Clustered theo
    tải: append-fact → BIGINT IDENTITY (PK_<t>_ID); point/join → natural (PK_<t>_NK); nhỏ → GUID.
    Natural giữ UQ_<t>_NK (idempotency). T_MASTER_PORTFOLIO: PK = C_MASTER_CODE (không GUID).
  DECIMAL: Tiền & Quantity = (20,0); Giá = (18,4); % / return / fee_rate = (10,6);
    Unit & Unit Price = (18,6); Weight (12,8); CA ratio (18,8); index_value (18,x).
==============================================================================*/

/*------------------------------------------------------------------ MASTER ---*/
CREATE TABLE T_MASTER_PORTFOLIO (
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_MASTER_NAME        NVARCHAR(200)   NULL,
    C_STATUS         VARCHAR(10)     NOT NULL CONSTRAINT DF_MASTER_PORTFOLIO_STATUS DEFAULT 'ACTIVE', -- ACTIVE|CLOSED
    C_INCEPTION_DATE DATE            NULL,
    C_MGMT_FEE_RATE  DECIMAL(10,6)   NOT NULL CONSTRAINT DF_MASTER_PORTFOLIO_FEE DEFAULT 0.01,        -- %/năm
    C_BENCHMARK_CODE VARCHAR(20)     NULL,   -- benchmark đối chiếu (vd 'VNINDEX','VN30') → T_BENCHMARK_DAILY
    CONSTRAINT PK_MASTER_PORTFOLIO PRIMARY KEY (C_MASTER_CODE)
);

-- Danh mục mẫu (FO tính & feed). Σ C_TARGET_WEIGHT theo (C_MASTER_CODE, C_EFFECTIVE_DATE) = 1.0
CREATE TABLE T_MASTER_PORTFOLIO_TICKER (
    PK_MASTER_PORTFOLIO_TICKER UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MASTER_PORTFOLIO_TICKER_PKID DEFAULT NEWID(),
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_EFFECTIVE_DATE DATE            NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_TARGET_WEIGHT  DECIMAL(12,8)   NOT NULL,
    CONSTRAINT PK_MASTER_PORTFOLIO_TICKER PRIMARY KEY CLUSTERED (PK_MASTER_PORTFOLIO_TICKER),
    CONSTRAINT UQ_MASTER_PORTFOLIO_TICKER_NK UNIQUE (C_MASTER_CODE, C_EFFECTIVE_DATE, C_TICKER)
);

-- SUB-ACCOUNT (tiểu khoản): 1 dòng/sub-account. C_SI_ACCOUNT = mã sub-account (CUST_CODE+đuôi), UNIQUE.
--   Close+reopen master ⇒ dòng MỚI (C_SI_ACCOUNT mới). Tối đa 1 ACTIVE / (KH×master) tại 1 thời điểm.
CREATE TABLE T_SI_PORTFOLIO (
    PK_SI_PORTFOLIO UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_PORTFOLIO_PKID DEFAULT NEWID(),
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,   -- mã sub-account (sub-index, customer-level) = CUST_CODE + đuôi
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,   -- master KH đầu tư → T_MASTER_PORTFOLIO.C_MASTER_CODE
    C_SUB_ACCOUNT_NO VARCHAR(32)     NULL,       -- số TK giao dịch tại FO (nếu khác C_SI_ACCOUNT)
    C_JOIN_DATE      DATE            NOT NULL,
    C_CLOSE_DATE     DATE            NULL,        -- ngày đóng sub-account (KH dừng đầu tư master)
    C_STATUS         VARCHAR(10)     NOT NULL CONSTRAINT DF_SI_PORTFOLIO_STATUS DEFAULT 'ACTIVE', -- ACTIVE|CLOSED
    C_INITIAL_AMOUNT DECIMAL(20,0)   NULL,
    C_SIP_AMOUNT     DECIMAL(20,0)   NULL,
    C_SIP_SCHEDULE   VARCHAR(50)     NULL,
    C_MGMT_FEE_RATE  DECIMAL(10,6)   NULL,    -- override; NULL = lấy theo T_MASTER_PORTFOLIO
    C_MIN_INVEST     DECIMAL(20,0)   NULL,
    CONSTRAINT PK_SI_PORTFOLIO PRIMARY KEY CLUSTERED (PK_SI_PORTFOLIO),
    CONSTRAINT UQ_SI_PORTFOLIO_NK UNIQUE (C_SI_ACCOUNT)   -- mã sub-account duy nhất toàn cục
);
-- Tối đa 1 sub-account ACTIVE / (KH × master) tại 1 thời điểm (closed thì được mở lại = dòng mới)
CREATE UNIQUE INDEX UQ_SI_PORTFOLIO_ACTIVE ON T_SI_PORTFOLIO (C_CUST_CODE, C_MASTER_CODE)
    WHERE C_STATUS = 'ACTIVE';

/*-------------------------------------------------------------- MARKET DATA ---*/
CREATE TABLE T_PRICE_DAILY (
    PK_PRICE_DAILY      UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PRICE_DAILY_PKID DEFAULT NEWID(),
    C_TICKER            VARCHAR(20)  NOT NULL,
    C_BUSINESS_DATE     DATE         NOT NULL,
    C_CLOSE_PRICE       DECIMAL(18,4) NOT NULL,
    C_ADJUSTED_REF_PRICE DECIMAL(18,4) NULL,
    CONSTRAINT PK_PRICE_DAILY_NK PRIMARY KEY CLUSTERED (C_BUSINESS_DATE, C_TICKER),  -- natural clustered (join MTM nóng)
    CONSTRAINT UQ_PRICE_DAILY_PKID UNIQUE NONCLUSTERED (PK_PRICE_DAILY)
);

CREATE TABLE T_CORPORATE_ACTION (
    PK_CORPORATE_ACTION  UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CORPORATE_ACTION_PKID DEFAULT NEWID(),
    C_TICKER             VARCHAR(20)  NOT NULL,
    C_EX_DATE            DATE         NOT NULL,
    C_CA_TYPE            VARCHAR(20)  NOT NULL,  -- CASH_DIV | STOCK_DIV | SPLIT | RIGHTS
    C_RATIO              DECIMAL(18,8) NULL,
    C_CASH_DIV_PER_SHARE DECIMAL(18,4) NULL,
    C_ADJUSTED_REF_PRICE DECIMAL(18,4) NULL,
    CONSTRAINT PK_CORPORATE_ACTION PRIMARY KEY CLUSTERED (PK_CORPORATE_ACTION),
    CONSTRAINT UQ_CORPORATE_ACTION_NK UNIQUE (C_TICKER, C_EX_DATE, C_CA_TYPE)
);

CREATE TABLE T_BENCHMARK_DAILY (
    PK_BENCHMARK_DAILY UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_BENCHMARK_DAILY_PKID DEFAULT NEWID(),
    C_BENCHMARK_CODE VARCHAR(20)     NOT NULL,   -- 'VNINDEX' | 'VN30' | …
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_INDEX_VALUE    DECIMAL(18,4)   NOT NULL,
    CONSTRAINT PK_BENCHMARK_DAILY PRIMARY KEY CLUSTERED (PK_BENCHMARK_DAILY),
    CONSTRAINT UQ_BENCHMARK_DAILY_NK UNIQUE (C_BENCHMARK_CODE, C_BUSINESS_DATE)
);

/*------------------------------------------------------- EVENT / LEDGER -------*/
CREATE TABLE T_REBALANCE_REQUEST (
    PK_REBALANCE_REQUEST UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_REBREQ_PKID DEFAULT NEWID(),
    C_REQUEST_ID     BIGINT IDENTITY(1,1) NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_TYPE           VARCHAR(20)     NOT NULL,  -- REBALANCE | DEPLOY | REDEEM
    C_STATUS         VARCHAR(20)     NOT NULL CONSTRAINT DF_REBREQ_STATUS DEFAULT 'NEW',
    CONSTRAINT PK_REBALANCE_REQUEST PRIMARY KEY CLUSTERED (PK_REBALANCE_REQUEST),
    CONSTRAINT UQ_REBALANCE_REQUEST_NK UNIQUE (C_REQUEST_ID)
);

-- HOLDINGS HISTORY theo KHOẢNG (INTERVAL/SCD-2) per SUB-ACCOUNT — full history, no-dup.
--   Reconstruct ngày D: WHERE C_VALID_FROM<=D AND (C_VALID_TO>D OR C_VALID_TO IS NULL).
CREATE TABLE T_SI_HOLDING_HIST (
    C_HOLDING_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,
    PK_SI_HOLDING_HIST UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_HOLDING_HIST_PKID DEFAULT NEWID(),
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,   -- sub-account (khóa nghiệp vụ)
    C_CUST_CODE      VARCHAR(10)     NOT NULL,   -- denormalized (query)
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,   -- denormalized (tổng hợp master)
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_VALID_FROM     DATE            NOT NULL,
    C_VALID_TO       DATE            NULL,
    C_QUANTITY       DECIMAL(20,0)   NOT NULL,
    C_AVG_COST       DECIMAL(18,4)   NULL,
    CONSTRAINT PK_SI_HOLDING_HIST_ID PRIMARY KEY CLUSTERED (C_HOLDING_HIST_ID),
    CONSTRAINT UQ_SI_HOLDING_HIST_PKID UNIQUE NONCLUSTERED (PK_SI_HOLDING_HIST),
    CONSTRAINT UQ_SI_HOLDING_HIST_NK UNIQUE (C_SI_ACCOUNT, C_TICKER, C_VALID_FROM)
) WITH (DATA_COMPRESSION = PAGE);
CREATE INDEX IX_SI_HOLDING_HIST_OPEN ON T_SI_HOLDING_HIST (C_SI_ACCOUNT, C_TICKER)
    INCLUDE (C_QUANTITY, C_AVG_COST) WHERE C_VALID_TO IS NULL;
-- (Cash vào qua SP_INGEST_CUSTOMER → state.C_CASH + diff T_SI_CASH_HIST; không có bảng feed batch.)

-- CASH HISTORY theo KHOẢNG (INTERVAL) per SUB-ACCOUNT — đối xứng holding_hist.
CREATE TABLE T_SI_CASH_HIST (
    C_CASH_HIST_ID   BIGINT IDENTITY(1,1) NOT NULL,
    PK_SI_CASH_HIST UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_CASH_HIST_PKID DEFAULT NEWID(),
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_VALID_FROM     DATE            NOT NULL,
    C_VALID_TO       DATE            NULL,
    C_CASH           DECIMAL(20,0)   NOT NULL,
    CONSTRAINT PK_SI_CASH_HIST_ID PRIMARY KEY CLUSTERED (C_CASH_HIST_ID),
    CONSTRAINT UQ_SI_CASH_HIST_PKID UNIQUE NONCLUSTERED (PK_SI_CASH_HIST),
    CONSTRAINT UQ_SI_CASH_HIST_NK UNIQUE (C_SI_ACCOUNT, C_VALID_FROM)
) WITH (DATA_COMPRESSION = PAGE);
CREATE INDEX IX_SI_CASH_HIST_OPEN ON T_SI_CASH_HIST (C_SI_ACCOUNT)
    INCLUDE (C_CASH) WHERE C_VALID_TO IS NULL;

-- External cashflow (nạp/rút) — SDI-side, per sub-account
CREATE TABLE T_SI_CASHFLOW_EVENT (
    PK_SI_CASHFLOW_EVENT UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_CASHFLOW_EVENT_PKID DEFAULT NEWID(),
    C_EVENT_ID       BIGINT IDENTITY(1,1) NOT NULL,
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_EVENT_TYPE     VARCHAR(20)     NOT NULL,  -- INITIAL|TOPUP|SIP|INTEREST_IN|WITHDRAW
    C_AMOUNT         DECIMAL(20,0)   NOT NULL,
    C_CREATED_TIME   DATETIME        NOT NULL CONSTRAINT DF_CF_CREATED DEFAULT GETDATE(),
    CONSTRAINT PK_SI_CASHFLOW_EVENT_ID PRIMARY KEY CLUSTERED (C_EVENT_ID),
    CONSTRAINT UQ_SI_CASHFLOW_EVENT_PKID UNIQUE NONCLUSTERED (PK_SI_CASHFLOW_EVENT)
);
CREATE INDEX IX_SI_CASHFLOW_EVENT_DATE ON T_SI_CASHFLOW_EVENT (C_BUSINESS_DATE) INCLUDE (C_SI_ACCOUNT, C_EVENT_TYPE, C_AMOUNT);

-- Unit thay đổi (ghi dòng khi có cashflow) per sub-account
CREATE TABLE T_SI_UNIT_LEDGER (
    C_SI_UNIT_LEDGER_ID BIGINT IDENTITY(1,1) NOT NULL,
    PK_SI_UNIT_LEDGER   UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_UNIT_LEDGER_PKID DEFAULT NEWID(),
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_CF_NET         DECIMAL(20,0)   NOT NULL,
    C_DELTA_UNIT     DECIMAL(18,6)   NOT NULL,
    C_UNIT           DECIMAL(18,6)   NOT NULL,
    CONSTRAINT PK_SI_UNIT_LEDGER_ID PRIMARY KEY CLUSTERED (C_SI_UNIT_LEDGER_ID),
    CONSTRAINT UQ_SI_UNIT_LEDGER_PKID UNIQUE NONCLUSTERED (PK_SI_UNIT_LEDGER),
    CONSTRAINT UQ_SI_UNIT_LEDGER_NK UNIQUE (C_SI_ACCOUNT, C_BUSINESS_DATE)
);

/*------------------------------------------- CURRENT STATE (roll-forward) -----*/
-- NAV/state HIỆN TẠI per SUB-ACCOUNT — 1 dòng, cập nhật tại chỗ mỗi EOD. Clustered theo C_SI_ACCOUNT.
CREATE TABLE T_SI_NAV_CURRENT (
    PK_SI_NAV_CURRENT UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_NAV_CURRENT_PKID DEFAULT NEWID(),
    C_SI_ACCOUNT       VARCHAR(20)   NOT NULL,
    C_CUST_CODE        VARCHAR(10)   NOT NULL,
    C_MASTER_CODE      VARCHAR(20)   NOT NULL,
    C_UNIT             DECIMAL(18,6) NOT NULL CONSTRAINT DF_CNC_UNIT DEFAULT 0,
    C_CASH             DECIMAL(20,0)  NOT NULL CONSTRAINT DF_CNC_CASH DEFAULT 0,
    C_PAYABLE_FEE      DECIMAL(20,0)  NOT NULL CONSTRAINT DF_CNC_PAY DEFAULT 0,
    C_LAST_NAV         DECIMAL(20,0)  NOT NULL CONSTRAINT DF_CNC_NAV DEFAULT 0,
    C_LAST_UNIT_PRICE  DECIMAL(18,6) NULL,
    C_STATUS           VARCHAR(10)    NOT NULL CONSTRAINT DF_CNC_STATUS DEFAULT 'ACTIVE', -- ACTIVE | CLOSED…
    C_LAST_BUSINESS_DATE DATE         NULL,                       -- ngày EOD compute gần nhất
    C_LAST_SYNC_DATE   DATE           NULL,                       -- watermark: ngày FO ingest gần nhất (GATE + guard forward)
    CONSTRAINT PK_SI_NAV_CURRENT_NK PRIMARY KEY CLUSTERED (C_SI_ACCOUNT),  -- natural clustered (MERGE/point roll-forward)
    CONSTRAINT UQ_SI_NAV_CURRENT_PKID UNIQUE NONCLUSTERED (PK_SI_NAV_CURRENT)
) WITH (DATA_COMPRESSION = PAGE);

-- Holdings HIỆN TẠI — FO nạp THẲNG mỗi EOD (overwrite). NGUỒN DUY NHẤT cho EOD core (MTM/agg).
CREATE TABLE T_SI_PORTFOLIO_HOLDING (
    PK_SI_PORTFOLIO_HOLDING UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_PORTFOLIO_HOLDING_PKID DEFAULT NEWID(),
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_QUANTITY       DECIMAL(20,0)   NOT NULL,
    C_AVG_COST       DECIMAL(18,4)   NULL,
    CONSTRAINT PK_SI_PORTFOLIO_HOLDING_NK PRIMARY KEY CLUSTERED (C_SI_ACCOUNT, C_TICKER),  -- natural clustered (MTM)
    CONSTRAINT UQ_SI_PORTFOLIO_HOLDING_PKID UNIQUE NONCLUSTERED (PK_SI_PORTFOLIO_HOLDING)
) WITH (DATA_COMPRESSION = PAGE);

/*--------------------------------------------- BẢNG WORK (transient/EOD) ------*/
CREATE TABLE T_EOD_WORK (
    C_BUSINESS_DATE   DATE           NOT NULL,
    C_SI_ACCOUNT      VARCHAR(20)    NOT NULL,
    C_CUST_CODE       VARCHAR(10)    NOT NULL,
    C_MASTER_CODE     VARCHAR(20)    NOT NULL,
    C_CASH            DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_PAYABLE_FEE     DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_LAST_NAV        DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_LAST_UNIT_PRICE DECIMAL(18,6) NULL,
    C_UNIT_PREV       DECIMAL(18,6) NOT NULL DEFAULT 0,
    C_CF_IN           DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_CF_OUT          DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_STOCK_VALUE     DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_NAV             DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_DAILY_PNL       DECIMAL(20,0)  NOT NULL DEFAULT 0,
    C_DELTA_UNIT      DECIMAL(18,6) NOT NULL DEFAULT 0,
    C_UNIT            DECIMAL(18,6) NOT NULL DEFAULT 0,
    C_UNIT_PRICE      DECIMAL(18,6) NULL,
    CONSTRAINT PK_EOD_WORK PRIMARY KEY CLUSTERED (C_BUSINESS_DATE, C_SI_ACCOUNT)  -- transient
);

/*--------------- PER-SUB-ACCOUNT NAV DAILY (lịch sử — chart FR-03) ------------*/
CREATE TABLE T_SI_NAV_BALANCE (
    C_NAV_BALANCE_ID   BIGINT IDENTITY(1,1) NOT NULL,                  -- clustered PK: append tuần tự (~2,5 tỷ)
    PK_SI_NAV_BALANCE UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_NAV_BALANCE_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_NAV            DECIMAL(20,0)   NOT NULL,
    C_UNIT           DECIMAL(18,6)  NOT NULL,
    C_UNIT_PRICE     DECIMAL(18,6)  NULL,
    C_DAILY_PNL      DECIMAL(20,0)   NOT NULL,
    C_DAILY_RETURN   DECIMAL(10,6)  NULL,
    CONSTRAINT PK_SI_NAV_BALANCE_ID PRIMARY KEY CLUSTERED (C_NAV_BALANCE_ID),
    CONSTRAINT UQ_SI_NAV_BALANCE_PKID UNIQUE NONCLUSTERED (PK_SI_NAV_BALANCE),
    CONSTRAINT UQ_SI_NAV_BALANCE_NK UNIQUE (C_BUSINESS_DATE, C_SI_ACCOUNT) -- idempotency
);

-- Sổ cái CỔ TỨC + PHÍ per sub-account, SPARSE — FO đẩy về (ingest, dedup C_SOURCE_EVENT_ID).
CREATE TABLE T_SI_FEE_INCOME (
    PK_SI_FEE_INCOME UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_FEE_INCOME_PKID DEFAULT NEWID(),
    C_EVENT_ID       BIGINT IDENTITY(1,1) NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_SI_ACCOUNT     VARCHAR(20)     NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_TYPE           VARCHAR(20)     NOT NULL,  -- DIVIDEND | CUSTODY_FEE | MGMT_FEE
    C_TICKER         VARCHAR(20)     NULL,
    C_AMOUNT         DECIMAL(20,0)   NOT NULL,
    C_SOURCE         VARCHAR(10)     NOT NULL CONSTRAINT DF_CFI_SRC DEFAULT 'FO',
    C_SOURCE_EVENT_ID VARCHAR(64)    NULL,      -- khóa idempotency FO (chống Kafka redelivery nhân đôi)
    C_CREATED_TIME   DATETIME        NOT NULL CONSTRAINT DF_CFI_CREATED DEFAULT GETDATE(),
    CONSTRAINT PK_SI_FEE_INCOME PRIMARY KEY CLUSTERED (PK_SI_FEE_INCOME),
    CONSTRAINT UQ_SI_FEE_INCOME_NK UNIQUE (C_EVENT_ID)
);
CREATE INDEX IX_SI_FEE_INCOME_DATE ON T_SI_FEE_INCOME (C_BUSINESS_DATE)
    INCLUDE (C_SI_ACCOUNT, C_MASTER_CODE, C_TYPE, C_AMOUNT);
CREATE UNIQUE INDEX UQ_SI_FEE_INCOME_SRCEVT ON T_SI_FEE_INCOME (C_SOURCE_EVENT_ID)
    WHERE C_SOURCE_EVENT_ID IS NOT NULL;

/*------------------------------------------------ MASTER-LEVEL DAILY (output) -*/
CREATE TABLE T_MASTER_INDEX_DAILY (
    PK_MASTER_INDEX_DAILY UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MASTER_INDEX_DAILY_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_INDEX_VALUE    DECIMAL(18,6)   NOT NULL,
    C_DAILY_RETURN   DECIMAL(10,6)  NULL,
    CONSTRAINT PK_MASTER_INDEX_DAILY PRIMARY KEY CLUSTERED (PK_MASTER_INDEX_DAILY),
    CONSTRAINT UQ_MASTER_INDEX_DAILY_NK UNIQUE (C_BUSINESS_DATE, C_MASTER_CODE)
);

CREATE TABLE T_MASTER_HOLDING_BALANCE (
    PK_MASTER_HOLDING_BALANCE UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MASTER_HOLDING_BALANCE_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_MASTER_CODE    VARCHAR(20)     NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_QUANTITY       DECIMAL(20,0)   NOT NULL,
    C_MARKET_PRICE   DECIMAL(18,4)   NOT NULL,
    C_MARKET_VALUE   DECIMAL(20,0)   NOT NULL,
    C_WEIGHT         DECIMAL(12,8)   NULL,
    CONSTRAINT PK_MASTER_HOLDING_BALANCE PRIMARY KEY CLUSTERED (PK_MASTER_HOLDING_BALANCE),
    CONSTRAINT UQ_MASTER_HOLDING_BALANCE_NK UNIQUE (C_BUSINESS_DATE, C_MASTER_CODE, C_TICKER)
);

-- NAV cấp MASTER/ngày — composition + NAV + hiệu suất (= Σ sub-account của master).
CREATE TABLE T_MASTER_NAV_BALANCE (
    PK_MASTER_NAV_BALANCE    UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MASTER_NAV_BALANCE_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE    DATE          NOT NULL,
    C_MASTER_CODE      VARCHAR(20)   NOT NULL,
    C_CASH             DECIMAL(20,0) NOT NULL,
    C_STOCK_VALUE      DECIMAL(20,0) NOT NULL,
    C_CASH_DIVIDEND    DECIMAL(20,0) NULL,
    C_CUSTODY_FEE      DECIMAL(20,0) NULL,
    C_MGMT_FEE_ACCRUED DECIMAL(20,0) NULL,    -- FO báo cáo tham khảo (SDI không tự accrue)
    C_PAYABLE_FEE      DECIMAL(20,0) NULL,
    C_TOTAL_ASSET      DECIMAL(20,0) NOT NULL,
    C_NAV              DECIMAL(20,0)  NOT NULL,
    C_UNIT             DECIMAL(18,6) NOT NULL,
    C_UNIT_PRICE       DECIMAL(18,6) NULL,
    C_DAILY_PNL        DECIMAL(20,0)  NOT NULL,
    C_DAILY_RETURN     DECIMAL(10,6) NULL,
    CONSTRAINT PK_MASTER_NAV_BALANCE PRIMARY KEY CLUSTERED (PK_MASTER_NAV_BALANCE),
    CONSTRAINT UQ_MASTER_NAV_BALANCE_NK UNIQUE (C_BUSINESS_DATE, C_MASTER_CODE)
);

-- NAV/state HIỆN TẠI cấp MASTER — 1 dòng/master, overwrite mỗi EOD (J11 MERGE từ T_MASTER_NAV_BALANCE @d).
CREATE TABLE T_MASTER_NAV_CURRENT (
    PK_MASTER_NAV_CURRENT  UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MASTER_NAV_CURRENT_PKID DEFAULT NEWID(),
    C_MASTER_CODE      VARCHAR(20)    NOT NULL,
    C_CASH             DECIMAL(20,0)  NOT NULL CONSTRAINT DF_SNC_CASH DEFAULT 0,
    C_STOCK_VALUE      DECIMAL(20,0)  NOT NULL CONSTRAINT DF_SNC_STOCK DEFAULT 0,
    C_TOTAL_ASSET      DECIMAL(20,0)  NOT NULL CONSTRAINT DF_SNC_TOTAL DEFAULT 0,
    C_LAST_NAV         DECIMAL(20,0)  NOT NULL CONSTRAINT DF_SNC_NAV DEFAULT 0,
    C_UNIT             DECIMAL(18,6) NOT NULL CONSTRAINT DF_SNC_UNIT DEFAULT 0,
    C_LAST_UNIT_PRICE  DECIMAL(18,6) NULL,
    C_LAST_BUSINESS_DATE DATE         NULL,
    CONSTRAINT PK_MASTER_NAV_CURRENT PRIMARY KEY CLUSTERED (PK_MASTER_NAV_CURRENT),
    CONSTRAINT UQ_MASTER_NAV_CURRENT_NK UNIQUE (C_MASTER_CODE)
);

/*------------------------------------------------ CONTROL / ORCHESTRATION -----*/
CREATE TABLE T_EOD_RUN (
    PK_EOD_RUN       UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_EOD_RUN_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_JOB            VARCHAR(40)     NOT NULL,
    C_STATUS         VARCHAR(10)     NOT NULL,  -- PENDING|RUNNING|DONE|FAILED
    C_ROWS           BIGINT          NULL,
    C_STARTED_AT     DATETIME        NULL,
    C_ENDED_AT       DATETIME        NULL,
    C_MESSAGE        NVARCHAR(2000)  NULL,
    CONSTRAINT PK_EOD_RUN PRIMARY KEY CLUSTERED (PK_EOD_RUN),
    CONSTRAINT UQ_EOD_RUN_NK UNIQUE (C_BUSINESS_DATE, C_JOB)
);
GO
