SET QUOTED_IDENTIFIER ON;  -- bắt buộc cho filtered index (open-row); sqlcmd mặc định OFF
SET ANSI_NULLS ON;
GO
/*==============================================================================
  SDI MODULE — TABLES (SQL Server)
  Naming convention:
    - Bảng:  prefix T_  (thay cho sdi_) , UPPERCASE
    - Cột:   prefix C_ (thường), UPPERCASE. Khóa nghiệp vụ giữ C_:
             C_SI_CODE (mã SI — PK của T_MASTER_PORTFOLIO; các bảng khác tham chiếu theo C_SI_CODE),
             C_CUST_CODE varchar10, C_TICKER, C_BENCHMARK_CODE, C_BUSINESS_DATE…
    - Khóa chính surrogate: MỌI bảng (trừ T_MASTER_PORTFOLIO) có cột GUID `PK_<table>`
             UNIQUEIDENTIFIER DEFAULT NEWID() làm **CLUSTERED PRIMARY KEY** = khóa public API/UI
             (IDOR-safe, random). Khóa natural/bigint cũ → giữ làm `UQ_<table>_NK` UNIQUE
             (đảm bảo idempotency/MERGE/NOT EXISTS của engine). FK tham chiếu = `FK_<table>`.
             T_MASTER_PORTFOLIO: PK = C_SI_CODE (mã nghiệp vụ, đã là khóa public — không GUID).
    - PK constraint: `PK_<table>` (trên cột GUID) | natural UNIQUE: `UQ_<table>_NK`
    - Stored procedure: prefix SP_   |   Function: prefix UDF_
  Tiền: DECIMAL(20,4) VND | Unit: DECIMAL(38,10) | Giá/tỷ trọng: DECIMAL
  PK clustered GUID (NEWID) ⇒ fragmentation cao trên bảng ghi-khối-lớn → prod: FILLFACTOR + REORG/REBUILD
  định kỳ; bảng lớn dùng CCI/partition (xem 00_INFRA.sql / SDI-db-architecture).
==============================================================================*/

/*------------------------------------------------------------------ MASTER ---*/
-- C_SI_CODE = PK + khóa public (mã nghiệp vụ, không phải int tuần tự → an toàn IDOR). KHÔNG GUID surrogate.
CREATE TABLE T_MASTER_PORTFOLIO (
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_SI_NAME        NVARCHAR(200)   NULL,
    C_STATUS         VARCHAR(10)     NOT NULL CONSTRAINT DF_MASTER_PORTFOLIO_STATUS DEFAULT 'ACTIVE', -- ACTIVE|CLOSED
    C_INCEPTION_DATE DATE            NULL,
    C_MGMT_FEE_RATE  DECIMAL(9,6)    NOT NULL CONSTRAINT DF_MASTER_PORTFOLIO_FEE DEFAULT 0.01,        -- %/năm
    C_BENCHMARK_CODE VARCHAR(20)     NULL,   -- benchmark đối chiếu (vd 'VNINDEX','VN30') → T_BENCHMARK_DAILY
    CONSTRAINT PK_MASTER_PORTFOLIO PRIMARY KEY (C_SI_CODE)
);

-- Danh mục mẫu (FO tính & feed). Σ C_TARGET_WEIGHT theo (C_SI_CODE, C_EFFECTIVE_DATE) = 1.0 (100% cổ phiếu)
CREATE TABLE T_MASTER_PORTFOLIO_TICKER (
    PK_MASTER_PORTFOLIO_TICKER UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_MASTER_PORTFOLIO_TICKER_PKID DEFAULT NEWID(),
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_EFFECTIVE_DATE DATE            NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_TARGET_WEIGHT  DECIMAL(12,8)   NOT NULL,
    CONSTRAINT PK_MASTER_PORTFOLIO_TICKER PRIMARY KEY CLUSTERED (PK_MASTER_PORTFOLIO_TICKER),
    CONSTRAINT UQ_MASTER_PORTFOLIO_TICKER_NK UNIQUE (C_SI_CODE, C_EFFECTIVE_DATE, C_TICKER)
    -- C_SI_CODE -> T_MASTER_PORTFOLIO.C_SI_CODE
);

-- Cấu hình đầu tư KH (1 dòng = 1 tiểu khoản = KH x SI)
CREATE TABLE T_INDEXING_PORTFOLIO (
    PK_INDEXING_PORTFOLIO UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_INDEXING_PORTFOLIO_PKID DEFAULT NEWID(),
    C_CUST_CODE     VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_SUB_ACCOUNT_NO VARCHAR(32)     NULL,
    C_JOIN_DATE      DATE            NOT NULL,
    C_STATUS         VARCHAR(10)     NOT NULL CONSTRAINT DF_INDEXING_PORTFOLIO_STATUS DEFAULT 'ACTIVE',
    C_INITIAL_AMOUNT DECIMAL(20,4)   NULL,
    C_SIP_AMOUNT     DECIMAL(20,4)   NULL,
    C_SIP_SCHEDULE   VARCHAR(50)     NULL,
    C_MGMT_FEE_RATE  DECIMAL(9,6)    NULL,    -- override; NULL = lấy theo T_MASTER_PORTFOLIO
    C_MIN_INVEST     DECIMAL(20,4)   NULL,
    CONSTRAINT PK_INDEXING_PORTFOLIO PRIMARY KEY CLUSTERED (PK_INDEXING_PORTFOLIO),
    CONSTRAINT UQ_INDEXING_PORTFOLIO_NK UNIQUE (C_CUST_CODE, C_SI_CODE)
    -- C_SI_CODE -> T_MASTER_PORTFOLIO.C_SI_CODE
);

/*-------------------------------------------------------------- MARKET DATA ---*/
CREATE TABLE T_PRICE_DAILY (
    PK_PRICE_DAILY      UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PRICE_DAILY_PKID DEFAULT NEWID(),
    C_TICKER            VARCHAR(20)  NOT NULL,
    C_BUSINESS_DATE     DATE         NOT NULL,
    C_CLOSE_PRICE       DECIMAL(18,4) NOT NULL,
    C_ADJUSTED_REF_PRICE DECIMAL(18,4) NULL,   -- giá tham chiếu điều chỉnh quyền (nếu có CA)
    CONSTRAINT PK_PRICE_DAILY_NK PRIMARY KEY CLUSTERED (C_BUSINESS_DATE, C_TICKER),  -- natural clustered (join MTM nóng)
    CONSTRAINT UQ_PRICE_DAILY_PKID UNIQUE NONCLUSTERED (PK_PRICE_DAILY)              -- GUID public API/UI
);

CREATE TABLE T_CORPORATE_ACTION (
    PK_CORPORATE_ACTION  UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CORPORATE_ACTION_PKID DEFAULT NEWID(),
    C_TICKER             VARCHAR(20)  NOT NULL,
    C_EX_DATE            DATE         NOT NULL,
    C_CA_TYPE            VARCHAR(20)  NOT NULL,  -- CASH_DIV | STOCK_DIV | SPLIT | RIGHTS
    C_RATIO              DECIMAL(18,8) NULL,     -- vd split/stock-div ratio
    C_CASH_DIV_PER_SHARE DECIMAL(18,4) NULL,
    C_ADJUSTED_REF_PRICE DECIMAL(18,4) NULL,
    CONSTRAINT PK_CORPORATE_ACTION PRIMARY KEY CLUSTERED (PK_CORPORATE_ACTION),
    CONSTRAINT UQ_CORPORATE_ACTION_NK UNIQUE (C_TICKER, C_EX_DATE, C_CA_TYPE)
);

-- Chỉ số thị trường NGOÀI (VN-Index, VN30…) — nạp từ market data, KHÔNG do SDI tính.
CREATE TABLE T_BENCHMARK_DAILY (
    PK_BENCHMARK_DAILY UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_BENCHMARK_DAILY_PKID DEFAULT NEWID(),
    C_BENCHMARK_CODE VARCHAR(20)     NOT NULL,   -- 'VNINDEX' | 'VN30' | …
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_INDEX_VALUE    DECIMAL(18,4)   NOT NULL,
    CONSTRAINT PK_BENCHMARK_DAILY PRIMARY KEY CLUSTERED (PK_BENCHMARK_DAILY),
    CONSTRAINT UQ_BENCHMARK_DAILY_NK UNIQUE (C_BENCHMARK_CODE, C_BUSINESS_DATE)
);

/*------------------------------------------------------- EVENT / LEDGER -------*/
-- SDI -> FO : trigger rebalance (KHÔNG chứa weights)
CREATE TABLE T_REBALANCE_REQUEST (
    PK_REBALANCE_REQUEST UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_REBREQ_PKID DEFAULT NEWID(),
    C_REQUEST_ID     BIGINT IDENTITY(1,1) NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_TYPE           VARCHAR(20)     NOT NULL,  -- REBALANCE | DEPLOY | REDEEM
    C_STATUS         VARCHAR(20)     NOT NULL CONSTRAINT DF_REBREQ_STATUS DEFAULT 'NEW',
    CONSTRAINT PK_REBALANCE_REQUEST PRIMARY KEY CLUSTERED (PK_REBALANCE_REQUEST),
    CONSTRAINT UQ_REBALANCE_REQUEST_NK UNIQUE (C_REQUEST_ID)
    -- C_SI_CODE -> T_MASTER_PORTFOLIO.C_SI_CODE
);

-- HOLDINGS HISTORY theo KHOẢNG hiệu lực (INTERVAL/temporal) — FULL history, KHÔNG trùng lặp.
--   1 dòng/(KH,SI,mã) chỉ ghi khi qty/avg_cost ĐỔI: valid_from..valid_to (NULL=open). Bất biến N năm = 1 dòng.
--   J14b maintain bằng DIFF current (T_INDEXING_PORTFOLIO_TICKER) vs open-row.
--   Reconstruct ngày D: WHERE C_VALID_FROM<=D AND (C_VALID_TO>D OR C_VALID_TO IS NULL).
CREATE TABLE T_CUSTOMER_HOLDING_HIST (
    C_HOLDING_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,                 -- clustered PK: append tuần tự (J14B insert nóng)
    PK_CUSTOMER_HOLDING_HIST UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CUSTOMER_HOLDING_HIST_PKID DEFAULT NEWID(), -- GUID public
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_VALID_FROM     DATE            NOT NULL,
    C_VALID_TO       DATE            NULL,        -- NULL = đang hiệu lực (open)
    C_QUANTITY       DECIMAL(20,4)   NOT NULL,
    C_AVG_COST       DECIMAL(18,4)   NULL,
    CONSTRAINT PK_CUSTOMER_HOLDING_HIST_ID PRIMARY KEY CLUSTERED (C_HOLDING_HIST_ID),
    CONSTRAINT UQ_CUSTOMER_HOLDING_HIST_PKID UNIQUE NONCLUSTERED (PK_CUSTOMER_HOLDING_HIST),  -- GUID public
    CONSTRAINT UQ_CUSTOMER_HOLDING_HIST_NK UNIQUE (C_CUST_CODE, C_SI_CODE, C_TICKER, C_VALID_FROM) -- idempotency/reconstruct
) WITH (DATA_COMPRESSION = PAGE);
CREATE INDEX IX_CUSTOMER_HOLDING_HIST_OPEN ON T_CUSTOMER_HOLDING_HIST (C_CUST_CODE, C_SI_CODE, C_TICKER)
    INCLUDE (C_QUANTITY, C_AVG_COST) WHERE C_VALID_TO IS NULL;
-- Prod: CCI + partition theo năm(valid_from) cho bảng HIST.
-- FO cash FEED (today): FO đẩy cash @d; SYNC_FO MERGE → state.cash. SHORT-retention (KHÔNG phải history).
CREATE TABLE T_FO_CASH_SYNC (
    PK_FO_CASH_SYNC  UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_FO_CASH_SYNC_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_CASH           DECIMAL(20,4)   NOT NULL,    -- tổng tiền (FO đã NET phí/thuế/SIP)
    CONSTRAINT PK_FO_CASH_SYNC PRIMARY KEY CLUSTERED (PK_FO_CASH_SYNC),
    CONSTRAINT UQ_FO_CASH_SYNC_NK UNIQUE (C_BUSINESS_DATE, C_CUST_CODE, C_SI_CODE)
);

-- CASH HISTORY theo KHOẢNG hiệu lực (INTERVAL) — FULL history, KHÔNG trùng lặp (đối xứng holding_hist).
CREATE TABLE T_CUSTOMER_CASH_HIST (
    C_CASH_HIST_ID   BIGINT IDENTITY(1,1) NOT NULL,                  -- clustered PK: append tuần tự (J14B insert)
    PK_CUSTOMER_CASH_HIST UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CUSTOMER_CASH_HIST_PKID DEFAULT NEWID(), -- GUID public
    C_CUST_CODE      VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_VALID_FROM     DATE            NOT NULL,
    C_VALID_TO       DATE            NULL,        -- NULL = đang hiệu lực (open)
    C_CASH           DECIMAL(20,4)   NOT NULL,
    CONSTRAINT PK_CUSTOMER_CASH_HIST_ID PRIMARY KEY CLUSTERED (C_CASH_HIST_ID),
    CONSTRAINT UQ_CUSTOMER_CASH_HIST_PKID UNIQUE NONCLUSTERED (PK_CUSTOMER_CASH_HIST),  -- GUID public
    CONSTRAINT UQ_CUSTOMER_CASH_HIST_NK UNIQUE (C_CUST_CODE, C_SI_CODE, C_VALID_FROM)   -- idempotency/reconstruct
) WITH (DATA_COMPRESSION = PAGE);
CREATE INDEX IX_CUSTOMER_CASH_HIST_OPEN ON T_CUSTOMER_CASH_HIST (C_CUST_CODE, C_SI_CODE)
    INCLUDE (C_CASH) WHERE C_VALID_TO IS NULL;

-- External cashflow (KHÔNG chứa income)
CREATE TABLE T_CASHFLOW_EVENT (
    PK_CASHFLOW_EVENT UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CASHFLOW_EVENT_PKID DEFAULT NEWID(),
    C_EVENT_ID       BIGINT IDENTITY(1,1) NOT NULL,
    C_CUST_CODE     VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_EVENT_TYPE     VARCHAR(20)     NOT NULL,  -- INITIAL|TOPUP|SIP|INTEREST_IN|WITHDRAW
    C_AMOUNT         DECIMAL(20,4)   NOT NULL,  -- luôn dương; chiều theo C_EVENT_TYPE
    C_CREATED_TIME   DATETIME2       NOT NULL CONSTRAINT DF_CF_CREATED DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CASHFLOW_EVENT_ID PRIMARY KEY CLUSTERED (C_EVENT_ID),               -- BIGINT IDENTITY clustered (append ~120M)
    CONSTRAINT UQ_CASHFLOW_EVENT_PKID UNIQUE NONCLUSTERED (PK_CASHFLOW_EVENT)         -- GUID public API/UI
);
CREATE INDEX IX_CASHFLOW_EVENT_DATE ON T_CASHFLOW_EVENT (C_BUSINESS_DATE) INCLUDE (C_CUST_CODE, C_SI_CODE, C_EVENT_TYPE, C_AMOUNT);

-- Unit thay đổi (ghi dòng khi có cashflow)
CREATE TABLE T_UNIT_LEDGER (
    C_UNIT_LEDGER_ID BIGINT IDENTITY(1,1) NOT NULL,                  -- clustered PK: append tuần tự (~120M)
    PK_UNIT_LEDGER   UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_UNIT_LEDGER_PKID DEFAULT NEWID(), -- GUID public
    C_CUST_CODE     VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_CF_NET         DECIMAL(20,4)   NOT NULL,
    C_DELTA_UNIT     DECIMAL(38,10)  NOT NULL,
    C_UNIT           DECIMAL(38,10)  NOT NULL,
    CONSTRAINT PK_UNIT_LEDGER_ID PRIMARY KEY CLUSTERED (C_UNIT_LEDGER_ID),
    CONSTRAINT UQ_UNIT_LEDGER_PKID UNIQUE NONCLUSTERED (PK_UNIT_LEDGER),               -- GUID public
    CONSTRAINT UQ_UNIT_LEDGER_NK UNIQUE (C_CUST_CODE, C_SI_CODE, C_BUSINESS_DATE)       -- idempotency
);

/*------------------------------------------- CURRENT STATE (roll-forward) -----*/
-- NAV/state HIỆN TẠI per tiểu khoản (KH×SI) — 1 dòng, cập nhật tại chỗ mỗi EOD.
CREATE TABLE T_CUSTOMER_NAV_CURRENT (
    PK_CUSTOMER_NAV_CURRENT UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CUSTOMER_NAV_CURRENT_PKID DEFAULT NEWID(),
    C_CUST_CODE       VARCHAR(10)   NOT NULL,
    C_SI_CODE          VARCHAR(20)   NOT NULL,
    C_UNIT             DECIMAL(38,10) NOT NULL CONSTRAINT DF_CNC_UNIT DEFAULT 0,
    C_CASH             DECIMAL(20,4)  NOT NULL CONSTRAINT DF_CNC_CASH DEFAULT 0,
    C_PAYABLE_FEE      DECIMAL(20,6)  NOT NULL CONSTRAINT DF_CNC_PAY DEFAULT 0, -- phí quản lý lũy kế (accrue)
    C_LAST_NAV         DECIMAL(20,4)  NOT NULL CONSTRAINT DF_CNC_NAV DEFAULT 0,
    C_LAST_UNIT_PRICE  DECIMAL(28,10) NULL,
    C_STATUS           VARCHAR(10)    NOT NULL CONSTRAINT DF_CNC_STATUS DEFAULT 'ACTIVE', -- ACTIVE | CLOSED…
    C_LAST_BUSINESS_DATE DATE         NULL,
    CONSTRAINT PK_CUSTOMER_NAV_CURRENT_NK PRIMARY KEY CLUSTERED (C_CUST_CODE, C_SI_CODE),  -- natural clustered (MERGE/point roll-forward)
    CONSTRAINT UQ_CUSTOMER_NAV_CURRENT_PKID UNIQUE NONCLUSTERED (PK_CUSTOMER_NAV_CURRENT)  -- GUID public API/UI
) WITH (DATA_COMPRESSION = PAGE);

-- Holdings HIỆN TẠI (~20M) — FO nạp THẲNG mỗi EOD (overwrite). NGUỒN DUY NHẤT cho EOD core (MTM/agg).
CREATE TABLE T_INDEXING_PORTFOLIO_TICKER (
    PK_INDEXING_PORTFOLIO_TICKER UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_INDEXING_PORTFOLIO_TICKER_PKID DEFAULT NEWID(),
    C_CUST_CODE     VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_QUANTITY       DECIMAL(20,4)   NOT NULL,
    C_AVG_COST       DECIMAL(18,4)   NULL,
    CONSTRAINT PK_INDEXING_PORTFOLIO_TICKER_NK PRIMARY KEY CLUSTERED (C_CUST_CODE, C_SI_CODE, C_TICKER),  -- natural clustered (MTM + FO load ~20M)
    CONSTRAINT UQ_INDEXING_PORTFOLIO_TICKER_PKID UNIQUE NONCLUSTERED (PK_INDEXING_PORTFOLIO_TICKER)       -- GUID public API/UI
) WITH (DATA_COMPRESSION = PAGE);
-- Prod: CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_INDEXING_PORTFOLIO_TICKER
--       ON T_INDEXING_PORTFOLIO_TICKER (C_CUST_CODE, C_SI_CODE, C_TICKER, C_QUANTITY);

/*--------------------------------------------- BẢNG WORK (transient/EOD) ------*/
-- Giá trị tính trong ngày @d (xóa/ghi lại mỗi run). (GUID PK chỉ để đồng nhất — bảng transient.)
CREATE TABLE T_EOD_WORK (
    C_BUSINESS_DATE   DATE           NOT NULL,
    C_CUST_CODE      VARCHAR(10)    NOT NULL,
    C_SI_CODE         VARCHAR(20)    NOT NULL,
    C_CASH            DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_PAYABLE_FEE     DECIMAL(20,6)  NOT NULL DEFAULT 0,
    C_LAST_NAV        DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_LAST_UNIT_PRICE DECIMAL(28,10) NULL,
    C_UNIT_PREV       DECIMAL(38,10) NOT NULL DEFAULT 0,
    C_CF_IN           DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_CF_OUT          DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_STOCK_VALUE     DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_NAV             DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_DAILY_PNL       DECIMAL(20,4)  NOT NULL DEFAULT 0,
    C_DELTA_UNIT      DECIMAL(38,10) NOT NULL DEFAULT 0,
    C_UNIT            DECIMAL(38,10) NOT NULL DEFAULT 0,
    C_UNIT_PRICE      DECIMAL(28,10) NULL,
    CONSTRAINT PK_EOD_WORK PRIMARY KEY CLUSTERED (C_BUSINESS_DATE, C_CUST_CODE, C_SI_CODE)  -- transient, KHÔNG GUID (không expose API)
);

/*--------------- PER-KH NAV DAILY (lịch sử — cần cho chart FR-03) -------------*/
-- ~2,5 tỷ dòng/10 năm → prod: CLUSTERED COLUMNSTORE + partition. GUID PK clustered (rowstore)
-- KHÔNG hợp bảng tỷ-dòng → prod cân nhắc chuyển PK GUID sang NONCLUSTERED + CCI clustered.
CREATE TABLE T_CUSTOMER_NAV_DAILY (
    C_NAV_DAILY_ID   BIGINT IDENTITY(1,1) NOT NULL,                  -- clustered PK: append tuần tự (bảng ~2,5 tỷ)
    PK_CUSTOMER_NAV_DAILY UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CUSTOMER_NAV_DAILY_PKID DEFAULT NEWID(), -- GUID public API/UI
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_CUST_CODE     VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_NAV            DECIMAL(20,4)   NOT NULL,
    C_UNIT           DECIMAL(38,10)  NOT NULL,
    C_UNIT_PRICE     DECIMAL(28,10)  NULL,
    C_DAILY_PNL      DECIMAL(20,4)   NOT NULL,
    C_DAILY_RETURN   DECIMAL(18,10)  NULL,
    CONSTRAINT PK_CUSTOMER_NAV_DAILY_ID PRIMARY KEY CLUSTERED (C_NAV_DAILY_ID),
    CONSTRAINT UQ_CUSTOMER_NAV_DAILY_PKID UNIQUE NONCLUSTERED (PK_CUSTOMER_NAV_DAILY),  -- GUID public
    CONSTRAINT UQ_CUSTOMER_NAV_DAILY_NK UNIQUE (C_BUSINESS_DATE, C_CUST_CODE, C_SI_CODE) -- idempotency
);

-- Sổ cái CỔ TỨC + PHÍ per (KH×SI), SPARSE (chỉ ghi khi có sự kiện) — FO đẩy về.
CREATE TABLE T_CUSTOMER_FEE_INCOME (
    PK_CUSTOMER_FEE_INCOME UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CUSTOMER_FEE_INCOME_PKID DEFAULT NEWID(),
    C_EVENT_ID       BIGINT IDENTITY(1,1) NOT NULL,
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_CUST_CODE     VARCHAR(10)     NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_TYPE           VARCHAR(20)     NOT NULL,  -- DIVIDEND | CUSTODY_FEE | MGMT_FEE
    C_TICKER         VARCHAR(20)     NULL,      -- mã (cho DIVIDEND); NULL cho phí cấp tài khoản
    C_AMOUNT         DECIMAL(20,4)   NOT NULL,  -- luôn dương; ý nghĩa theo C_TYPE
    C_SOURCE         VARCHAR(10)     NOT NULL CONSTRAINT DF_CFI_SRC DEFAULT 'FO',
    C_CREATED_TIME   DATETIME2       NOT NULL CONSTRAINT DF_CFI_CREATED DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CUSTOMER_FEE_INCOME PRIMARY KEY CLUSTERED (PK_CUSTOMER_FEE_INCOME),
    CONSTRAINT UQ_CUSTOMER_FEE_INCOME_NK UNIQUE (C_EVENT_ID)
);
CREATE INDEX IX_CUSTOMER_FEE_INCOME_DATE ON T_CUSTOMER_FEE_INCOME (C_BUSINESS_DATE)
    INCLUDE (C_CUST_CODE, C_SI_CODE, C_TYPE, C_AMOUNT);

/*------------------------------------------------ SI-LEVEL DAILY (output) -----*/
CREATE TABLE T_SI_INDEX_DAILY (
    PK_SI_INDEX_DAILY UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_INDEX_DAILY_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_INDEX_VALUE    DECIMAL(18,6)   NOT NULL,
    C_DAILY_RETURN   DECIMAL(18,10)  NULL,
    CONSTRAINT PK_SI_INDEX_DAILY PRIMARY KEY CLUSTERED (PK_SI_INDEX_DAILY),
    CONSTRAINT UQ_SI_INDEX_DAILY_NK UNIQUE (C_BUSINESS_DATE, C_SI_CODE)
);

CREATE TABLE T_SI_HOLDING_DAILY (
    PK_SI_HOLDING_DAILY UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_HOLDING_DAILY_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_SI_CODE        VARCHAR(20)     NOT NULL,
    C_TICKER         VARCHAR(20)     NOT NULL,
    C_QUANTITY       DECIMAL(20,4)   NOT NULL,
    C_MARKET_PRICE   DECIMAL(18,4)   NOT NULL,
    C_MARKET_VALUE   DECIMAL(20,4)   NOT NULL,
    C_WEIGHT         DECIMAL(12,8)   NULL,
    CONSTRAINT PK_SI_HOLDING_DAILY PRIMARY KEY CLUSTERED (PK_SI_HOLDING_DAILY),
    CONSTRAINT UQ_SI_HOLDING_DAILY_NK UNIQUE (C_BUSINESS_DATE, C_SI_CODE, C_TICKER)
);

-- NAV cấp SI/ngày — NGUỒN NAV SI-level DUY NHẤT (composition tài sản + hiệu suất).
CREATE TABLE T_SI_NAV_DAILY (
    PK_SI_NAV_DAILY    UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_NAV_DAILY_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE    DATE          NOT NULL,
    C_SI_CODE          VARCHAR(20)   NOT NULL,
    -- composition tài sản
    C_CASH             DECIMAL(20,4) NOT NULL,
    C_STOCK_VALUE      DECIMAL(20,4) NOT NULL,
    C_CASH_DIVIDEND    DECIMAL(20,4) NULL,
    C_CUSTODY_FEE      DECIMAL(20,4) NULL,
    C_MGMT_FEE_ACCRUED DECIMAL(20,6) NULL,    -- FO báo cáo tham khảo (SDI không tự accrue)
    C_PAYABLE_FEE      DECIMAL(20,6) NULL,
    C_TOTAL_ASSET      DECIMAL(20,4) NOT NULL,
    -- NAV + hiệu suất
    C_NAV              DECIMAL(20,4)  NOT NULL,
    C_UNIT             DECIMAL(38,10) NOT NULL,
    C_UNIT_PRICE       DECIMAL(28,10) NULL,
    C_DAILY_PNL        DECIMAL(20,4)  NOT NULL,
    C_DAILY_RETURN     DECIMAL(18,10) NULL,
    CONSTRAINT PK_SI_NAV_DAILY PRIMARY KEY CLUSTERED (PK_SI_NAV_DAILY),
    CONSTRAINT UQ_SI_NAV_DAILY_NK UNIQUE (C_BUSINESS_DATE, C_SI_CODE)
);

-- NAV/state HIỆN TẠI cấp SI — 1 dòng/SI (~100), overwrite mỗi EOD (J11 MERGE từ T_SI_NAV_DAILY @d).
CREATE TABLE T_SI_NAV_CURRENT (
    PK_SI_NAV_CURRENT  UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_SI_NAV_CURRENT_PKID DEFAULT NEWID(),
    C_SI_CODE          VARCHAR(20)    NOT NULL,
    C_CASH             DECIMAL(20,4)  NOT NULL CONSTRAINT DF_SNC_CASH DEFAULT 0,
    C_STOCK_VALUE      DECIMAL(20,4)  NOT NULL CONSTRAINT DF_SNC_STOCK DEFAULT 0,
    C_TOTAL_ASSET      DECIMAL(20,4)  NOT NULL CONSTRAINT DF_SNC_TOTAL DEFAULT 0,
    C_LAST_NAV         DECIMAL(20,4)  NOT NULL CONSTRAINT DF_SNC_NAV DEFAULT 0,
    C_UNIT             DECIMAL(38,10) NOT NULL CONSTRAINT DF_SNC_UNIT DEFAULT 0,
    C_LAST_UNIT_PRICE  DECIMAL(28,10) NULL,
    C_LAST_BUSINESS_DATE DATE         NULL,
    CONSTRAINT PK_SI_NAV_CURRENT PRIMARY KEY CLUSTERED (PK_SI_NAV_CURRENT),
    CONSTRAINT UQ_SI_NAV_CURRENT_NK UNIQUE (C_SI_CODE)
);

/*------------------------------------------------ CONTROL / ORCHESTRATION -----*/
CREATE TABLE T_EOD_RUN (
    PK_EOD_RUN       UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_EOD_RUN_PKID DEFAULT NEWID(),
    C_BUSINESS_DATE  DATE            NOT NULL,
    C_JOB            VARCHAR(40)     NOT NULL,
    C_STATUS         VARCHAR(10)     NOT NULL,  -- PENDING|RUNNING|DONE|FAILED
    C_ROWS           BIGINT          NULL,
    C_STARTED_AT     DATETIME2       NULL,
    C_ENDED_AT       DATETIME2       NULL,
    C_MESSAGE        NVARCHAR(2000)  NULL,
    CONSTRAINT PK_EOD_RUN PRIMARY KEY CLUSTERED (PK_EOD_RUN),
    CONSTRAINT UQ_EOD_RUN_NK UNIQUE (C_BUSINESS_DATE, C_JOB)
);
GO
