/*==============================================================================
  PM TOOL — PERF BENCH (P5). Seed THẲNG multi-master × multi-KH × multi-day rồi
  đo từng SP serve-layer (06_PM_API). KHÔNG qua EOD (seed bulk cho scale).
  Chạy sau 01/02/05/06 trên DB sạch. sqlcmd vars: NMASTER, NCUST(/master), NDAYS.
    T_SI_NAV_BALANCE rows = NMASTER × NCUST × NDAYS  (10×5000×250 = 12.5M ≈ prod).
  Giá trị synthetic varied (đủ cho STDEV/return có variance) — KHÔNG dùng verify số
  (số đúng đã verify ở 07_PM_SMOKE), chỉ đo THỜI GIAN.
==============================================================================*/
SET NOCOUNT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @nMaster INT=$(NMASTER), @nCust INT=$(NCUST), @nDays INT=$(NDAYS);
DECLARE @start DATE='2025-01-01';

PRINT CONCAT('PM BENCH seed: nMaster=',@nMaster,' nCust/master=',@nCust,' nDays=',@nDays,
             ' → subaccount=',@nMaster*@nCust,' NAV_BALANCE=',CAST(@nMaster AS BIGINT)*@nCust*@nDays);

TRUNCATE TABLE T_SI_NAV_BALANCE;       TRUNCATE TABLE T_SI_NAV_CURRENT;
TRUNCATE TABLE T_SI_PORTFOLIO;         TRUNCATE TABLE T_MASTER_NAV_BALANCE;
TRUNCATE TABLE T_MASTER_NAV_CURRENT;   TRUNCATE TABLE T_MASTER_INDEX_DAILY;
TRUNCATE TABLE T_MASTER_HOLDING_BALANCE; TRUNCATE TABLE T_MASTER_PORTFOLIO_TICKER;
TRUNCATE TABLE T_BENCHMARK_DAILY;      DELETE FROM T_MASTER_PM_CONFIG;
DELETE FROM T_MASTER_PORTFOLIO;

-- tally
;WITH L0(n) AS (SELECT 1 FROM (VALUES(1),(1),(1),(1),(1),(1),(1),(1),(1),(1))v(n)),
 NUMS AS (SELECT TOP (1000000) ROW_NUMBER() OVER(ORDER BY(SELECT NULL)) n
          FROM L0 a,L0 b,L0 c,L0 d,L0 e,L0 f)
SELECT n INTO #num FROM NUMS;
CREATE UNIQUE CLUSTERED INDEX IX_num ON #num(n);

SELECT n AS m, CONCAT('M',FORMAT(n,'00')) AS mcode INTO #m FROM #num WHERE n<=@nMaster;
SELECT n AS c INTO #c FROM #num WHERE n<=@nCust;
SELECT n AS dseq, DATEADD(DAY,n-1,@start) AS dt INTO #day FROM #num WHERE n<=@nDays;
CREATE UNIQUE CLUSTERED INDEX IX_m ON #m(m); CREATE UNIQUE CLUSTERED INDEX IX_c ON #c(c);
CREATE UNIQUE CLUSTERED INDEX IX_day ON #day(dseq);

-- sub-accounts (si = 'S'+master+'_'+cust)
SELECT CONCAT('S',FORMAT(m.m,'00'),'_',FORMAT(c.c,'00000')) AS si,
       CONCAT('K',FORMAT(m.m,'00'),'_',FORMAT(c.c,'00000')) AS cust,
       m.mcode, m.m, c.c
INTO #sa FROM #m m CROSS JOIN #c c;
CREATE CLUSTERED INDEX IX_sa ON #sa(mcode, si);

INSERT T_MASTER_PORTFOLIO (C_MASTER_CODE,C_MASTER_NAME,C_STATUS,C_INCEPTION_DATE,C_MGMT_FEE_RATE,C_BENCHMARK_CODE)
SELECT mcode, CONCAT(N'Bench Master ',m), 'ACTIVE', @start, 0.01, 'VNI' FROM #m;

-- target weights: 3 mốc rebalance (đầu, giữa, cuối kỳ) × 5 mã
INSERT T_MASTER_PORTFOLIO_TICKER (C_MASTER_CODE,C_EFFECTIVE_DATE,C_TICKER,C_TARGET_WEIGHT)
SELECT m.mcode, e.dt, CONCAT('TK',t.n), 0.20
FROM #m m
CROSS JOIN (SELECT dt FROM #day WHERE dseq IN (1, @nDays/2, @nDays-1)) e
CROSS JOIN (SELECT n FROM #num WHERE n<=5) t;

-- master holdings balance (per master per day × 5 mã) — cho rebalance detail
INSERT T_MASTER_HOLDING_BALANCE (C_BUSINESS_DATE,C_MASTER_CODE,C_TICKER,C_QUANTITY,C_MARKET_PRICE,C_MARKET_VALUE,C_WEIGHT)
SELECT d.dt, m.mcode, CONCAT('TK',t.n), 1000+d.dseq+t.n, 20, (1000+d.dseq+t.n)*20, 0.20
FROM #m m CROSS JOIN #day d CROSS JOIN (SELECT n FROM #num WHERE n<=5) t;

INSERT T_BENCHMARK_DAILY (C_BENCHMARK_CODE,C_BUSINESS_DATE,C_INDEX_VALUE)
SELECT 'VNI', dt, 800.0 + dseq*0.3 FROM #day;

-- master index daily (varied return)
INSERT T_MASTER_INDEX_DAILY (C_BUSINESS_DATE,C_MASTER_CODE,C_INDEX_VALUE,C_DAILY_RETURN)
SELECT d.dt, m.mcode, 1000.0 + d.dseq*0.4,
       CASE WHEN d.dseq=1 THEN NULL ELSE CAST(0.0003 + 0.0002*(((d.dseq+m.m)%7)-3) AS DECIMAL(10,6)) END
FROM #m m CROSS JOIN #day d;

-- master nav daily
INSERT T_MASTER_NAV_BALANCE
 (C_BUSINESS_DATE,C_MASTER_CODE,C_CASH,C_STOCK_VALUE,C_TOTAL_ASSET,C_NAV,C_UNIT,C_UNIT_PRICE,C_DAILY_PNL,C_DAILY_RETURN,C_CASH_IN,C_CASH_OUT,C_TOTAL_ACCOUNT)
SELECT d.dt, m.mcode,
       CAST(@nCust AS BIGINT)*3000000, CAST(@nCust AS BIGINT)*97000000, CAST(@nCust AS BIGINT)*100000000,
       CAST(@nCust AS BIGINT)*100000000, 10000, 10000.0+d.dseq*2, 0,
       CASE WHEN d.dseq=1 THEN NULL ELSE 0.0005 END,
       CASE WHEN d.dseq%10=0 THEN CAST(@nCust AS BIGINT)*500000 ELSE 0 END,
       CASE WHEN d.dseq%15=0 THEN CAST(@nCust AS BIGINT)*200000 ELSE 0 END,
       @nCust
FROM #m m CROSS JOIN #day d;

INSERT T_MASTER_NAV_CURRENT
 (C_MASTER_CODE,C_CASH,C_PENDING_CASH,C_DIV_CASH,C_STOCK_VALUE,C_TOTAL_ASSET,C_LAST_NAV,C_UNIT,C_LAST_UNIT_PRICE,C_TOTAL_ACCOUNT,C_LAST_BUSINESS_DATE)
SELECT m.mcode, CAST(@nCust AS BIGINT)*3000000,0,0, CAST(@nCust AS BIGINT)*97000000, CAST(@nCust AS BIGINT)*100000000,
       CAST(@nCust AS BIGINT)*100000000, 10000, 10000.0+@nDays*2, @nCust, (SELECT MAX(dt) FROM #day)
FROM #m m;

INSERT T_SI_PORTFOLIO (C_SI_ACCOUNT,C_CUST_CODE,C_MASTER_CODE,C_JOIN_DATE,C_STATUS)
SELECT si,cust,mcode,@start,'ACTIVE' FROM #sa;

INSERT T_SI_NAV_CURRENT
 (C_SI_ACCOUNT,C_CUST_CODE,C_MASTER_CODE,C_UNIT,C_CASH,C_PENDING_CASH,C_DIV_CASH,C_PAYABLE_FEE,C_LAST_NAV,C_LAST_UNIT_PRICE,C_STATUS,C_LAST_BUSINESS_DATE)
SELECT si,cust,mcode,10000, 1000000*(1+c%5),0,0,0, 100000000+c, CAST(10000.0+@nDays*3+(c%50) AS DECIMAL(18,6)),'ACTIVE',(SELECT MAX(dt) FROM #day)
FROM #sa;

-- BIG: per-KH per-day NAV_BALANCE (varied unit_price + daily_return)
INSERT T_SI_NAV_BALANCE (C_BUSINESS_DATE,C_SI_ACCOUNT,C_CUST_CODE,C_MASTER_CODE,C_NAV,C_PAYABLE_FEE,C_UNIT,C_UNIT_PRICE,C_DAILY_PNL,C_DAILY_RETURN)
SELECT d.dt, sa.si, sa.cust, sa.mcode,
       100000000 + d.dseq*1000 + sa.c, 0, 10000,
       CAST(10000.0 + (d.dseq-1)*3 + (sa.c%50) AS DECIMAL(18,6)), 0,
       CASE WHEN d.dseq=1 THEN NULL ELSE CAST(0.0003 + 0.0004*(((d.dseq+sa.c)%11)-5) AS DECIMAL(10,6)) END
FROM #sa sa CROSS JOIN #day d;

-- TE prefix-sum cumulative: seed bằng WINDOW (1 pass) thay 250 lần gọi SP_EOD_TE_ACCUM (cùng ngữ nghĩa).
;WITH bse AS (
    SELECT b.C_NAV_BALANCE_ID, b.C_SI_ACCOUNT, b.C_BUSINESS_DATE,
           CASE WHEN b.C_DAILY_RETURN IS NULL OR idx.C_DAILY_RETURN IS NULL THEN NULL
                ELSE CAST(b.C_DAILY_RETURN - idx.C_DAILY_RETURN AS FLOAT) END AS a
    FROM T_SI_NAV_BALANCE b
    INNER JOIN T_MASTER_INDEX_DAILY idx ON idx.C_MASTER_CODE=b.C_MASTER_CODE AND idx.C_BUSINESS_DATE=b.C_BUSINESS_DATE
), accum AS (
    SELECT C_NAV_BALANCE_ID,
        SUM(a)     OVER (PARTITION BY C_SI_ACCOUNT ORDER BY C_BUSINESS_DATE ROWS UNBOUNDED PRECEDING) AS car,
        SUM(a*a)   OVER (PARTITION BY C_SI_ACCOUNT ORDER BY C_BUSINESS_DATE ROWS UNBOUNDED PRECEDING) AS car2,
        SUM(CASE WHEN a IS NOT NULL THEN 1 ELSE 0 END)
                   OVER (PARTITION BY C_SI_ACCOUNT ORDER BY C_BUSINESS_DATE ROWS UNBOUNDED PRECEDING) AS cnt
    FROM bse
)
UPDATE b SET b.C_ACCUM_ACTIVE_RET=ISNULL(c.car,0), b.C_ACCUM_ACTIVE_RET_SQ=ISNULL(c.car2,0), b.C_RET_DAY_COUNT=c.cnt
FROM T_SI_NAV_BALANCE b INNER JOIN accum c ON c.C_NAV_BALANCE_ID=b.C_NAV_BALANCE_ID;

DROP TABLE #num,#m,#c,#day,#sa;
DECLARE @rows BIGINT = (SELECT COUNT_BIG(*) FROM T_SI_NAV_BALANCE);
PRINT CONCAT('Seeded NAV_BALANCE rows = ', @rows);
GO

/*--------------------------------- ĐO -----------------------------------------*/
DECLARE @t0 DATETIME2, @ms INT, @M VARCHAR(20)='M01';
DECLARE @ec INT, @em NVARCHAR(400);

-- mỗi SP chạy 2 lần (run1=cold/compile, run2=warm). In ms.
DECLARE @r INT;
SET @r=1;
WHILE @r<=2 BEGIN
  SET @t0=SYSDATETIME(); EXEC SP_GET_MASTER_OVERVIEW @M,'INCEPTION', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US2 OVERVIEW(INCEPTION) = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_MASTER_OVERVIEW @M,'1Y', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US2 OVERVIEW(1Y) = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_MASTER_PERFORMANCE @M,'INCEPTION',NULL, @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US3 PERFORMANCE(INCEPTION) = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_MASTER_REBALANCE_DETAIL @M,'2025-06-01', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US3 REBALANCE_DETAIL = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_MASTER_PNL_DIST @M,'INCEPTION', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US4 PNL_DIST(INCEPTION) = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_MASTER_TOP_KH @M,'INCEPTION',20,'DESC', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US5 TOP_KH(INCEPTION) = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_PM_OVERVIEW_ALL 'INCEPTION','AUM', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US1 OVERVIEW_ALL(INCEPTION) = ',@ms,' ms');

  SET @t0=SYSDATETIME(); EXEC SP_GET_PM_OVERVIEW_ALL '1Y','AUM', @p_err_code=@ec OUTPUT, @p_err_msg=@em OUTPUT;
  SET @ms=DATEDIFF(MILLISECOND,@t0,SYSDATETIME()); PRINT CONCAT('[run',@r,'] US1 OVERVIEW_ALL(1Y) = ',@ms,' ms');
  SET @r=@r+1;
END
GO
